export const languageCode =  {
    options: [
        { value: 'az', displayValue: 'Azerbaijani' },
        { value: 'sq', displayValue: 'Albanian' },
        { value: 'ar', displayValue: 'Arabic' },
        { value: 'bn', displayValue: 'Bengali' },
        { value: 'bg', displayValue: 'Bulgarian' },
        { value: 'ca', displayValue: 'Catalan' },
        { value: 'zh', displayValue: 'Chinese' },
        { value: 'hr', displayValue: 'Croatian' },
        { value: 'cs', displayValue: 'Czech' },
        { value: 'da', displayValue: 'Danish' },
        { value: 'nl', displayValue: 'Dutch' },
        { value: 'en', displayValue: 'English' },
        { value: 'et', displayValue: 'Estonian' },
        { value: 'fa', displayValue: 'Farsi' },
        { value: 'fi', displayValue: 'Finnish' },
        { value: 'fr', displayValue: 'French' },
        { value: 'de', displayValue: 'German' },
        { value: 'el', displayValue: 'Greek' },
        { value: 'he', displayValue: 'Hebrew' },
        { value: 'hi', displayValue: 'Hindi' },
        { value: 'hu', displayValue: 'Hungarian' },
        { value: 'is', displayValue: 'Icelandic' },
        { value: 'id', displayValue: 'Indonesian' },
        { value: 'ii', displayValue: 'Italian' },
        { value: 'ja', displayValue: 'Japanese' },
        { value: 'jv', displayValue: 'Javanese' },
        { value: 'ko', displayValue: 'Korean' },
        { value: 'lv', displayValue: 'Latvian' },
        { value: 'lt', displayValue: 'Lithuanian' },
        { value: 'ms', displayValue: 'Malay' },
        { value: 'nb', displayValue: 'Norwegian' },
        { value: 'pl', displayValue: 'Polish' },
        { value: 'pt', displayValue: 'Portuguese' },
        { value: 'ro', displayValue: 'Romanian' },
        { value: 'ru', displayValue: 'Russian' },
        { value: 'sk', displayValue: 'Slovak' },
        { value: 'si', displayValue: 'Slovenian' },
        { value: 'es', displayValue: 'Spanish' },
        { value: 'sw', displayValue: 'Swahili' },
        { value: 'sv', displayValue: 'Swedish' },
        { value: 'tl', displayValue: 'Tagalog' },
        { value: 'th', displayValue: 'Thai' },
        { value: 'tr', displayValue: 'Turkish' },
        { value: 'uk', displayValue: 'Ukrainian' },
        { value: 'ur', displayValue: 'Urdu' },
        { value: 'vi', displayValue: 'Vietnamese' }
    ],
    value: 'en',
}